CREATE OR REPLACE FUNCTION validate_user() RETURNS TRIGGER AS $$
BEGIN
    IF LENGTH(NEW.name) < 6
    THEN
        RAISE EXCEPTION 'INVALID USER NAME';
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;


CREATE or REPLACE TRIGGER verify_user BEFORE INSERT OR UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE  validate_user();
